import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part I: Introduction',
      items: [
        'chapter-1',
        'chapter-2',
      ],
    },
    {
      type: 'category',
      label: 'Part II: Advanced Topics',
      items: [
        'chapter-3',
        'chapter-4',
      ],
    },
  ],

  // You can also use autogeneration if you prefer
  // bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
